name: Run Container Scan on Super Mario Docker Image with Quality Gate

on:
  push:
    branches:
      - "__disabled__"

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set VERSION
        run: |
          echo "VERSION=$(($(cat version.txt) + 1))" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull and Save Docker Image
        run: |
          docker pull docker.io/dbakeytest/supermariogitopsproject:${VERSION}
          docker save docker.io/dbakeytest/supermariogitopsproject:${VERSION} \
            -o supermariolatestdockerimage.tar

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          input: supermariolatestdockerimage.tar
          severity: CRITICAL,HIGH
          exit-code: '0'
